---
#
# Ansible tasks for the levant role
#
- name: check if rules file exists
  stat: 
    path: "{{ levant_home }}/levant"
  register: levant_installed

- name: download levant
  unarchive:
    src:      "{{ levant_download }}"
    dest:     "{{ levant_home }}"
    mode:     "a+x"
    owner:    "{{ levant_usr }}"
    group:    "{{ levant_grp }}
    remote_src: yes
  register: levant_was_downloaded
  when: levant_installed.stat.exists == False
  
- name: set executable ownership, group and permissions
  file:
    path: "{{ levant_home }}/levant"
    owner: "{{ levant_usr }}"
    group: "{{ levant_grp }}"
    mode: '0755'
  when: levant_installed.stat.exists == True

